version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./prod-volume/db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-h', 'db', '-U', '${DB_USERNAME}']
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    image: registry.digitalocean.com/grade-master-hub/server
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: production
    container_name: server
    restart: unless-stopped
    env_file: .env.production
    ports:
      - ${PORT}:${PORT}
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./prod-volume/pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
