version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./dev-volumes/db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DB_USERNAME}']
      interval: 5s
      timeout: 5s
      retries: 5

  maildev:
    image: maildev/maildev
    container_name: maildev
    restart: unless-stopped
    environment:
      MAILDEV_SMTP_PORT: ${MAILER_PORT}
    ports:
      - 1080:1080
      - ${MAILER_PORT}:${MAILER_PORT}

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: server
    restart: unless-stopped
    env_file: .env.development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    network_mode: host

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./dev-volumes/pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
