version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./dev-volume/db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DB_USERNAME}']
      interval: 5s
      timeout: 5s
      retries: 5

  maildev:
    image: maildev/maildev
    container_name: maildev
    restart: unless-stopped
    environment:
      MAILDEV_SMTP_PORT: ${MAILER_PORT}
      MAILDEV_WEB_USER: ${MAILDEV_WEB_USER}
      MAILDEV_WEB_PASS: ${MAILDEV_WEB_PASS}
      MAILDEV_HTTPS: ${MAILDEV_HTTPS}
      MAILDEV_HTTPS_KEY: ${MAILDEV_HTTPS_KEY}
      MAILDEV_HTTPS_CERT: ${MAILDEV_HTTPS_CERT}
      MAILDEV_INCOMING_USER: ${MAILER_USER}
      MAILDEV_INCOMING_PASS: ${MAILER_PASSWORD}
    ports:
      - 1080:1080
      - ${MAILER_PORT}:${MAILER_PORT}

  server:
    image: registry.digitalocean.com/grade-master-hub/server-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: server
    restart: unless-stopped
    env_file: .env.development
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${PORT}:${PORT}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./dev-volume/pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
