FROM node:20-alpine as development

WORKDIR /app

ENV NODE_ENV development

COPY --chown=node:node package.json yarn.lock ./
COPY --chown=node:node . .

RUN yarn

RUN yarn build

USER node

CMD ["sh", "-c", "yarn seeds:dev && yarn start:dev"]
