FROM node:20-alpine as development

WORKDIR /app

ENV NODE_ENV development

COPY --chown=node:node . .

RUN mkdir -p /app/node_modules && chown -R node:node /app

RUN yarn

RUN yarn build

USER node

CMD ["sh", "-c", "yarn seeds:dev && node dist/main.js"]
