version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./prod-volumes/db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  server:
    image: registry.digitalocean.com/grade-master-hub/server
    env_file: .env.production
    ports:
      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    volumes:
      - ./prod-volumes/pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
