export enum ENotificationType {
  GRADE_COMPOSITION_FINALIZED = 'GRADE_COMPOSITION_FINALIZED',
  GRADE_REVIEW_REQUESTED = 'GRADE_REVIEW_REQUESTED',
  MARK_REVIEW_DECISION = 'MARK_REVIEW_DECISION',
  COMMENT = 'COMMENT',
  COMMENT_REPLY = 'COMMENT_REPLY',
}
